---
title: "Regression"
author: "Prabidhik KC"
date: "2022-11-22"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
## loading the necessary libraries
library(tidyverse)
library(gov50data)
```


## Looking at the data
```{r}
health
health <- health %>% 
  drop_na()
health %>% 
  ggplot(aes(x = steps_lag, y = weight)) +
  geom_point(color = "steelblue1") +
  labs(x = "steps yesterday (in 1000s)",
       y = "weight (in pounds")

mean_wt_5ksteps <- health %>% 
  filter(round(steps_lag) == 5) %>% 
  summarize(mean(weight)) %>% 
  pull()


mean_wt_5ksteps

```
```{r}
health %>% 
  ggplot(aes(x = steps_lag, y = weight)) +
  geom_point(color = "steelblue1") +
  labs(x = "steps yesterday (in 1000s)",
       y = "weight (in pounds") +
  geom_vline(xintercept = c(4.5, 5.5), linetype = "dashed") +
  geom_point(aes(x = 5, y = mean_wt_5ksteps), size = 3, color = "red")
```
```{r}
health %>% 
  ggplot(aes(x = steps_lag, y = weight)) +
  geom_point(color = "steelblue1") +
  labs(x = "steps yesterday (in 1000s)",
       y = "weight (in pounds") +
  stat_summary_bin(fun = "mean", geom = "point", size = 2, color = "red", binwidth = 0.5)
```
```{r}
health %>% 
  ggplot(aes(x = steps_lag, y = weight)) +
  geom_point(color = "steelblue1") +
  labs(x = "steps yesterday (in 1000s)",
       y = "weight (in pounds") +
  geom_smooth(method = "lm", se = FALSE, color = "red", size = 1.5) +
  stat_summary_bin(fun = "mean", geom = "point", size = 2, color = "indianred1", binwidth = 0.5)
```

## Lienar Models 

```{r}
fit <- lm(weight ~ steps, data = health)
fit
```

```{r}
library(broom)
augment(fit) %>% 
  ggplot(aes(x = steps, y = .resid)) +
  geom_point()
```
```{r}
coef(fit)
```

The coefficient on steps is `r coef(fit)[2]`

```{r}
augment(fit) %>% 
  summarize(mean(.resid))
```
```{r}
augment(fit) %>% 
  summarize(mean(.resid))
```

```{r}
library(gov50data)
midterms
```
```{r}
fit <- lm(seat_change ~ approval, data = midterms)
fit
fit_rdi <- lm(seat_change ~ rdi_change, data = midterms)
fit_rdi

summary(fit)$r.squared
summary(fit_rdi)$r.squared

glance(fit)
glance(fit)$r.squared

midterms %>% 
  ggplot(aes(x = approval, y = seat_change)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, color = "red")

midterms %>% 
  ggplot(aes(x = rdi_change, y = seat_change)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, color = "red")
```


## Multiple regressions
```{r}
mult.fit <- lm(seat_change ~ approval + rdi_change, data = midterms)
mult.fit

midterms <- midterms %>% 
  mutate(
    noise = runif(nrow(midterms))
  )
midterms

noise.fit <- lm(seat_change ~ approval + rdi_change + noise, data = midterms)

fit
mult.fit
noise.fit

glance(fit)
glance(mult.fit)
glance(noise.fit)
```

## Predicted values

```{r}
library(modelr)

midterms %>% 
  filter(year == 2022) %>% 
  add_predictions(mult.fit)
  
```
```{r}
midterms %>% 
  filter(year == 2022) %>% 
  gather_predictions(fit, mult.fit, noise.fit)
```

```{r}
data("progresa", package = "qss")

cct <- as_tibble(progresa) %>% 
  select(treatment, pri2000s, t2000)

cct

cct %>% 
  group_by(treatment) %>% 
  summarize(t2000 = mean(t2000)) %>% 
  pivot_wider(names_from = treatment, values_from = t2000) %>% 
  mutate(ATE = `1` - `0`)

lm(pri2000s ~ treatment, data = cct)


```



